spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root@2726
  jpa:
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: ERROR