spring:
  application:
    name: Store API
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200
    refreshTokenExpiration: 604800
  profiles:
    active: dev
server:
  port: 8082
logging:
  level:
    org:
      springframework:
        security: ERROR